### ISSUE TITLE
[BUG]: output file

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/team_comm_tools#299]
It seems like the output files are not being put where I expect:

in my feature builder instantiation, with my jupyter notebook working in the `analysis` directory, i use parameters:
```
        vector_directory = f"./vector_data/",
        output_file_path_chat_level = f"./chat_level_features.csv",
        output_file_path_user_level = f"./user_level_features.csv",
        output_file_path_conv_level = f"./conversation_level_features.csv",
```

However, my output files are actually saved in:
<img width="253" alt="image" src="https://github.com/user-attachments/assets/2cf08dfa-1faf-456d-9c4f-c4cc21a53bb2">

**Comment by xehu** [comment]
Hi James! This is a bit confusing, but this is a feature rather than a bug. See the worked example: https://conversational-featurizer.readthedocs.io/en/latest/examples.htmlWe want to keep the outputs tidy, so we automatically organize everything into a folder called “output.” But we didn’t want to force the user to pass us a path in particular format, so we modify all paths under the hood, such that the output file path is always in a folder called “output,” with a sub folder pertaining to the type of feature being generated.On Sep 25, 2024, at 12:37 PM, James Houghton ***@***.***> wrote:﻿
It seems like the output files are not being put where I expect:
in my feature builder instantiation, with my jupyter notebook working in the analysis directory, i use parameters:
        vector_directory = f"./vector_data/",
        output_file_path_chat_level = f"./chat_level_features.csv",
        output_file_path_user_level = f"./user_level_features.csv",
        output_file_path_conv_level = f"./conversation_level_features.csv",

However, my output files are actually saved in:
image.png (view on web)

**Comment by JamesPHoughton** [comment]
Oooh, if i do this:
```
output_file_path_chat_level = f"../data/chat_level_features.csv",
```
I get this:
<img width="349" alt="image" src="https://github.com/user-attachments/assets/f8d2e206-05c5-478c-9a0d-d09f07d274b4">
that's quite counterintuitive

**Comment by JamesPHoughton** [comment]
Why not just have a default path for those things that is `/output/turn/turn_level_features.csv`, and then make this parameter optional, but have it actually use the path as a proper relative path. That'll be less confusing, and probably less code...

**Comment by xehu** [comment]
@JamesPHoughton yeah, this is an Issue - https://github.com/Watts-Lab/team_comm_tools/issues/286

Maybe after we chat today I'll implement some changes! To directly address your questions, though, it seems like you are running the featurizer with `turns=True`, which is why we are automatically changing the name from `chats` to `turns`. If you change it to `False`, you won't get that behavior.
